module.exports = {
  table_clients: 'clients',
  table_water_connection: 'water_connection',
  table_type_clients: 'type_clients',
  table_prices: 'prices',
  table_client_level: 'client_level',
  table_transaction: 'transaction',
  table_users: 'users',
  table_time_connection: 'time_connection',
  table_reports: 'reports',
  table_type_reports: 'type_reports',
  table_colonias: 'colonias',
  table_type_transactions: 'type_transaction',
  table_debts: 'debts',
  table_type_debts: 'type_debts',
}